In [1]:
import numpy as np
np.set_printoptions(precision=4)

# Initialize weights
W_0 = np.array([[1, 0, 1],
                [-1, -1, 1]], dtype=float)  # Hidden layer weights
W_1 = np.array([[0, 1, -1]], dtype=float)   # Output layer weights

# Input and target
X = np.array([[1, -1, 1],
              [0, -1, 1]], dtype=float)     # Shape: (2, 2)
t = np.array([[0, 0, 1]], dtype=float)   # Shape: (1, 2)

# Hyperparameters
f_1 = "Lin"
f_2 = "ReLU"
lr = 1
MAX_EPOCHS = 1

# Activation Functions
def USigmoid(x, direction='F'):
    fx = 1 / (1 + np.exp(-x))
    return fx if direction == 'F' else fx * (1 - fx)

def BSigmoid(x, direction='F'):
    fx = (1 - np.exp(-x)) / (1 + np.exp(-x))
    return fx if direction == 'F' else 0.5 * (1 - fx ** 2)

def TanH(x, direction='F'):
    fx = np.tanh(x)
    return fx if direction == 'F' else 1 - fx ** 2

def ReLU(x, direction='F'):
    return np.maximum(0, x) if direction == 'F' else (x > 0).astype(float)

def Lin(x, direction='F'):
    return x if direction == 'F' else np.ones_like(x)

# Wrapper for activation
def activation(Z, fcn="Lin", direction='F'):
    return np.array([globals()[fcn](z, direction) for z in Z]).reshape(-1, 1)

# A_0 = np.vstack((np.ones((1, 1)), x.reshape(-1, 1)))

# Training loop
for ep in range(MAX_EPOCHS):
    print('\nEPOCH-', ep + 1, '=' * 80)
    for itr, (x, y) in enumerate(zip(X.T, t.T)):
        print(f'\nITER-{itr + 1} ' + '-' * 80)

        # Forward Pass: Input -> Hidden
        A_0 = x.reshape(-1, 1)

        # Conditionally add bias to A_0
        if W_0.shape[1] == A_0.shape[0] + 1:
            A_0 = np.vstack((np.ones((1, 1)), A_0))  # Add bias at the top
            print('Bias added to A_0')

        Z_1 = W_0 @ A_0
        A_1 = activation(Z_1, f_1)

        # Forward Pass: Hidden -> Output
        # Conditionally add bias to A_1
        if W_1.shape[1] == A_1.shape[0] + 1:
            A_1 = np.vstack((np.ones((1, 1)), A_1))  # Add bias at the top
            print('Bias added to A_1')

        Z_2 = W_1 @ A_1
        A_2 = activation(Z_2, f_2)

        print(f'A_0 (input):\n{A_0}')
        print(f'Z_1 (hidden pre-activation):\n{Z_1}')
        print(f'A_1 (hidden post-activation):\n{A_1}')
        print(f'Z_2 (output pre-activation):\n{Z_2}')
        print(f'A_2 (output post-activation):\n{A_2}')

       # Backward Pass: Output -> Hidden
        delta_2 = (A_2 - y.reshape(-1, 1)) * activation(Z_2, f_2, 'B')
        dW_1 = delta_2 @ A_1.T

        # Remove bias from W_1 if necessary
        if W_1.shape[1] == Z_1.shape[0] + 1:
            W_1_no_bias = W_1[:, 1:]
            print("Bias column removed from W_1 for backpropagation.")
        else:
            W_1_no_bias = W_1

        print(W_1_no_bias)

        # Backward Pass: Hidden -> Input
        delta_1 = (W_1_no_bias.T @ delta_2) * activation(Z_1, f_1, 'B')
        dW_0 = delta_1 @ A_0.T

        # Update weights
        W_1 -= lr * dW_1
        W_0 -= lr * dW_0

        print(f'dW_1:\n{dW_1}')
        print(f'dW_0:\n{dW_0}')
        print(f'Updated W_1:\n{W_1}')
        print(f'Updated W_0:\n{W_0}')




EPOCH- 1 ================================================================================

ITER-1 --------------------------------------------------------------------------------
Bias added to A_0
Bias added to A_1
A_0 (input):
[[1.]
 [1.]
 [0.]]
Z_1 (hidden pre-activation):
[[ 1.]
 [-2.]]
A_1 (hidden post-activation):
[[ 1.]
 [ 1.]
 [-2.]]
Z_2 (output pre-activation):
[[3.]]
A_2 (output post-activation):
[[3.]]
Bias column removed from W_1 for backpropagation.
[[ 1. -1.]]
dW_1:
[[ 3.  3. -6.]]
dW_0:
[[ 3.  3.  0.]
 [-3. -3.  0.]]
Updated W_1:
[[-3. -2.  5.]]
Updated W_0:
[[-2. -3.  1.]
 [ 2.  2.  1.]]

ITER-2 --------------------------------------------------------------------------------
Bias added to A_0
Bias added to A_1
A_0 (input):
[[ 1.]
 [-1.]
 [-1.]]
Z_1 (hidden pre-activation):
[[ 0.]
 [-1.]]
A_1 (hidden post-activation):
[[ 1.]
 [ 0.]
 [-1.]]
Z_2 (output pre-activation):
[[-8.]]
A_2 (output post-activation):
[[0.]]
Bias column removed from W_1 for backpropagation.
[[-2.  5.