In [ ]:
# import numpy as np

# # Initial weights
# W_0 = np.array([[1, 0, 1]], dtype=float)
# print("Initial W_0 shape:", W_0.shape)  # (1, 3)

# # Targets
# t = np.array([[1 ,-1 ,-1]], dtype=float)

# # Inputs
# X = np.array([
#     [1, 1, -1],
#     [0, 1, 1]
# ], dtype=float)
# print("X shape:", X.shape)  # (2, 3)

# # Activation function name
# f_1 = "Lin"

# # Learning rate
# lr = 0.1

# # Activation Functions
# def USigmoid(x, direction):
#     if direction == 'F':
#         return 1 / (1 + np.exp(-x))
#     else:  # derivative
#         fx = USigmoid(x, 'F')
#         return fx * (1 - fx)

# def BSigmoid(x, direction):
#     if direction == 'F':
#         return (1 - np.exp(-x)) / (1 + np.exp(-x))
#     else:
#         fx = BSigmoid(x, 'F')
#         return 0.5 * (1 - fx ** 2)

# def ReLU(x, direction):
#     if direction == 'F':
#         return np.maximum(0, x)
#     else:
#         return float(x > 0)

# def Lin(x, direction):
#     if direction == 'F':
#         return x
#     else:
#         return 1

# # Activation wrapper
# def activation(Z, fcn="Lin", direction='F'):
#     Z = np.atleast_1d(Z)
#     return np.array([globals()[fcn](z, direction) for z in Z])

# # Training loop
# MAX_EPOCH = 1

# # Pad bias term to input
# print('Pad bias at top of input')
# A_0 = np.vstack((np.ones((1, X.shape[1])), X))
# print(A_0)

# for ep in range(MAX_EPOCH):
#     print('\nEPOCH-', ep + 1, '=' * 80)
#     for itr, (x, y) in enumerate(zip(A_0.T, t.T)):
#         print('\nITER-', itr + 1, '-' * 80)

#         print(f'{y = }')

#         # Forward pass
#         print('Input -> Output')
#         Z_1 = W_0 @ x
#         print(f'{Z_1 = }')
#         A_1 = activation(Z_1, f_1)
#         print(f'{A_1 = }')

#         # Backward pass
#         print('\nOutput -> Input')
#         Error = 0.5 * (A_1 - y) ** 2
#         print(f'{Error = }')
#         dE_dW = (A_1 - y) * activation(Z_1, f_1, 'B') * x
#         print(f'{dE_dW = }')

#         # Weight update
#         W_0 = W_0 - lr * dE_dW
#         print(f'{W_0 = }')


Initial W_0 shape: (1, 3)
X shape: (2, 3)
Pad bias at top of input
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 0.  1.  1.]]

EPOCH- 1 ================================================================================

ITER- 1 --------------------------------------------------------------------------------
y = array([1.])
Input -> Output
Z_1 = array([1.])
A_1 = array([1.])

Output -> Input
Error = array([0.])
dE_dW = array([0., 0., 0.])
W_0 = array([[1., 0., 1.]])

ITER- 2 --------------------------------------------------------------------------------
y = array([-1.])
Input -> Output
Z_1 = array([2.])
A_1 = array([2.])

Output -> Input
Error = array([4.5])
dE_dW = array([3., 3., 3.])
W_0 = array([[ 0.7, -0.3,  0.7]])

ITER- 3 --------------------------------------------------------------------------------
y = array([-1.])
Input -> Output
Z_1 = array([1.7])
A_1 = array([1.7])

Output -> Input
Error = array([3.645])
dE_dW = array([ 2.7, -2.7,  2.7])
W_0 = array([[ 0.43, -0.03,  0.43]])


In [4]:
import numpy as np
import tensorflow as tf

# Initial weights
W_0 = tf.Variable([[1.0, 0.0, 1.0]], dtype=tf.float32)
print("Initial W_0 shape:", W_0.shape)

# Targets
t = tf.constant([[1.0, -1.0, -1.0]], dtype=tf.float32)

# Inputs
X = tf.constant([
    [1.0, 1.0, -1.0],
    [0.0, 1.0, 1.0]
], dtype=tf.float32)
print("X shape:", X.shape)

# Activation function name
f_1 = "Lin"

# Learning rate
lr = 0.1

# Activation Functions
def USigmoid(x):
    return tf.math.sigmoid(x)

def USigmoid_deriv(x):
    fx = tf.math.sigmoid(x)
    return fx * (1 - fx)

def BSigmoid(x):
    return (1 - tf.exp(-x)) / (1 + tf.exp(-x))

def BSigmoid_deriv(x):
    fx = BSigmoid(x)
    return 0.5 * (1 - tf.square(fx))

def ReLU(x):
    return tf.nn.relu(x)

def ReLU_deriv(x):
    return tf.cast(x > 0, tf.float32)

def Lin(x):
    return x

def Lin_deriv(x):
    return tf.ones_like(x)

# Activation function dictionary
activation_map = {
    "USigmoid": (USigmoid, USigmoid_deriv),
    "BSigmoid": (BSigmoid, BSigmoid_deriv),
    "ReLU": (ReLU, ReLU_deriv),
    "Lin": (Lin, Lin_deriv),
}

# Select activation function and its derivative
activation_fn, activation_deriv = activation_map[f_1]

# Add bias term to input (pad bias row at the top)
A_0 = np.vstack((np.ones((1, X.shape[1])), X))
A_0 = tf.constant(A_0, dtype=tf.float32)

# Training loop
MAX_EPOCH = 1

# Epoch loop
# Epoch loop
for ep in range(MAX_EPOCH):
    print(f"\nEPOCH-{ep + 1} " + "=" * 80)

    for itr, (x, y) in enumerate(zip(tf.transpose(A_0), tf.transpose(t))):
        print(f"\nITER-{itr + 1} " + "-" * 80)

        # Forward pass
        Z_1 = tf.matmul(W_0, tf.reshape(x, [-1, 1]))
        A_1 = activation_fn(Z_1)

        print(f"Target (y): {y.numpy()[0]:.2f}")
        print(f"Z_1 (Weighted sum): {Z_1.numpy()[0][0]:.4f}")
        print(f"A_1 (Activated output): {A_1.numpy()[0][0]:.4f}")

        # Error and gradient
        Error = 0.5 * (A_1 - y) ** 2
        dE_dZ = (A_1 - y) * activation_deriv(Z_1)
        dE_dW = tf.matmul(dE_dZ, tf.reshape(x, [1, -1]))

        print(f"Error: {Error.numpy()[0][0]:.4f}")
        print(f"dE_dW (Gradients): {np.round(dE_dW.numpy(), 4)}")

        # Update weights
        W_0.assign_sub(lr * dE_dW)
        print(f"Updated W_0: {np.round(W_0.numpy(), 4)}")


Initial W_0 shape: (1, 3)
X shape: (2, 3)

EPOCH-1 ================================================================================

ITER-1 --------------------------------------------------------------------------------
Target (y): 1.00
Z_1 (Weighted sum): 1.0000
A_1 (Activated output): 1.0000
Error: 0.0000
dE_dW (Gradients): [[0. 0. 0.]]
Updated W_0: [[1. 0. 1.]]

ITER-2 --------------------------------------------------------------------------------
Target (y): -1.00
Z_1 (Weighted sum): 2.0000
A_1 (Activated output): 2.0000
Error: 4.5000
dE_dW (Gradients): [[3. 3. 3.]]
Updated W_0: [[ 0.7 -0.3  0.7]]

ITER-3 --------------------------------------------------------------------------------
Target (y): -1.00
Z_1 (Weighted sum): 1.7000
A_1 (Activated output): 1.7000
Error: 3.6450
dE_dW (Gradients): [[ 2.7 -2.7  2.7]]
Updated W_0: [[ 0.43 -0.03  0.43]]
